### ISSUE TITLE
Rotation Forst not working with scikit

### ISSUE THREAD

**Issue by MariaChry** [Liam-E2/RotationForest#1]
It seems that rotation forest is not working anymore with the current scikit-learn version

**Comment by Liam-E2** [comment]
Hey, thanks for bringing this to my attention! Haven't thought about this repo in a long time - there's a couple forks which might be of interest to you, but I don't have the bandwidth to maintain this currently. Feel free to send in a PR, or if you send more info about the error, I can try and take a look sometime in the next month.
